project_name: chinesesubfinder

env:
    - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - sudo apt install gcc-multilib
    - sudo apt install gcc-mingw-w64
    - sudo apt install binutils-mingw-w64
builds:
  - env:
      - CGO_ENABLED=0
      - CXX=x86_64-w64-mingw32-g++
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
      - linux
    goarch:
      - amd64
    main: ./cmd/chinesesubfinder/main.go

archives:
  - id: archive
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^TestData:'
      - '^TestCode:'