on:
  push:
  pull_request:
    branches:
      - master

# for cache
# checkout https://github.com/magnetikonline/action-golang-cache
# https://www.lorenzobettini.it/2020/12/caching-dependencies-in-github-actions/

name: Test

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      # only test gss for now
      # go test ./... for all
      # after the testdata problems resolved
      run: go test ./internal/pkg/gss/
